# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import communication_pb2 as proto_dot_communication__pb2


class CommunicationStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendComm = channel.unary_unary(
                '/communication.Communication/SendComm',
                request_serializer=proto_dot_communication__pb2.RequestComm.SerializeToString,
                response_deserializer=proto_dot_communication__pb2.ReplyComm.FromString,
                )


class CommunicationServicer(object):
    """The greeting service definition.
    """

    def SendComm(self, request, context):
        """Sends a ...
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendComm': grpc.unary_unary_rpc_method_handler(
                    servicer.SendComm,
                    request_deserializer=proto_dot_communication__pb2.RequestComm.FromString,
                    response_serializer=proto_dot_communication__pb2.ReplyComm.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'communication.Communication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communication(object):
    """The greeting service definition.
    """

    @staticmethod
    def SendComm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/communication.Communication/SendComm',
            proto_dot_communication__pb2.RequestComm.SerializeToString,
            proto_dot_communication__pb2.ReplyComm.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
