# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/communication.proto',
  package='communication',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/communication.proto\x12\rcommunication\"\x85\x01\n\x0bRequestComm\x12\x17\n\x0f\x63heck_connexion\x18\x01 \x01(\t\x12\x15\n\rcode_etudiant\x18\x02 \x01(\t\x12\x14\n\x0ctype_message\x18\x03 \x01(\t\x12\x11\n\tmsg_accel\x18\x04 \x01(\t\x12\x0b\n\x03img\x18\x05 \x01(\t\x12\x10\n\x08\x64\x61teTime\x18\x06 \x01(\t\"\x83\x01\n\tReplyComm\x12\x17\n\x0f\x63heck_connexion\x18\x01 \x01(\t\x12\x15\n\rcode_etudiant\x18\x02 \x01(\t\x12\x14\n\x0ctype_message\x18\x03 \x01(\t\x12\x11\n\tmsg_accel\x18\x04 \x01(\t\x12\x0b\n\x03img\x18\x05 \x01(\t\x12\x10\n\x08\x64\x61teTime\x18\x06 \x01(\t2S\n\rCommunication\x12\x42\n\x08SendComm\x12\x1a.communication.RequestComm\x1a\x18.communication.ReplyComm\"\x00\x62\x06proto3'
)




_REQUESTCOMM = _descriptor.Descriptor(
  name='RequestComm',
  full_name='communication.RequestComm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='check_connexion', full_name='communication.RequestComm.check_connexion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code_etudiant', full_name='communication.RequestComm.code_etudiant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_message', full_name='communication.RequestComm.type_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_accel', full_name='communication.RequestComm.msg_accel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='communication.RequestComm.img', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='communication.RequestComm.dateTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=178,
)


_REPLYCOMM = _descriptor.Descriptor(
  name='ReplyComm',
  full_name='communication.ReplyComm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='check_connexion', full_name='communication.ReplyComm.check_connexion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code_etudiant', full_name='communication.ReplyComm.code_etudiant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_message', full_name='communication.ReplyComm.type_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_accel', full_name='communication.ReplyComm.msg_accel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='communication.ReplyComm.img', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='communication.ReplyComm.dateTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=312,
)

DESCRIPTOR.message_types_by_name['RequestComm'] = _REQUESTCOMM
DESCRIPTOR.message_types_by_name['ReplyComm'] = _REPLYCOMM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestComm = _reflection.GeneratedProtocolMessageType('RequestComm', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCOMM,
  '__module__' : 'proto.communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.RequestComm)
  })
_sym_db.RegisterMessage(RequestComm)

ReplyComm = _reflection.GeneratedProtocolMessageType('ReplyComm', (_message.Message,), {
  'DESCRIPTOR' : _REPLYCOMM,
  '__module__' : 'proto.communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.ReplyComm)
  })
_sym_db.RegisterMessage(ReplyComm)



_COMMUNICATION = _descriptor.ServiceDescriptor(
  name='Communication',
  full_name='communication.Communication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendComm',
    full_name='communication.Communication.SendComm',
    index=0,
    containing_service=None,
    input_type=_REQUESTCOMM,
    output_type=_REPLYCOMM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMUNICATION)

DESCRIPTOR.services_by_name['Communication'] = _COMMUNICATION

# @@protoc_insertion_point(module_scope)
